n_it: 1000
output_dir: 'C:\Codigos\CNN_Solver\dataset\generated\'

domain:
  geom: 'cartesian'
  mat: 'cart_dirichlet'
  bcs: 'dirichlet'
  xmin: 0.0
  xmax: 1.0e-2
  nnx: 101
  ymin: 0.0
  ymax: 1.0e-2
  nny: 101
  zmin: 0.0
  zmax: 1.0e-2
  nnz: 101