general:
    name_case: 'interface_15.pth'
    data_dir: 'dataset/generated/domain.npy' 


globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 101                                # Number of points in x direction
    nny: 101                                # Number of points in y direction
    xmin: 0.0
    ymin: 0.0
    xmax: 5.0
    ymax: 5.0
    interface_center:
        x: 2.5
        y: 2.5
    interface_radius: 1.5
    epsilon_inside: 1.0
    epsilon_outside: 80.0

arch:
    scales:
        scale_0: [[1, 30, 20], [40, 30, 1]]
        scale_1: [[20, 20, 20], [40, 20, 20]]
        scale_2: [[20, 16, 16, 20], [40, 16, 16, 20]]
        scale_3: [[20, 20, 20], [40, 20, 20]]
        scale_4: [[20, 60, 20]]
    kernel_sizes: 3
        

data_loader:
    batch_size: 64


loss:
    args:
        bound_weight: 5.0e+0                  # Weighting of the loss on the boundaries (float)
        lapl_weight: 5.0e+4
        interface_weight: 4.0e+5                # Weighting of the loss on the Laplacian (float)
        optimizer_lr: 4.e-3   

trainer:
    epochs: 200                            # Number of epochs

