general:
    name_case: 'Unet4_ks3_rf50.pth'
    data_dir: 'dataset/generated/random.npy' 


arch:
    model: "UNet"
    arch_dir: 'Archs/Unet_ks3_rf50.yml'
    type: 'UNet4'


globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 101                                # Number of points in x direction
    nny: 101                                # Number of points in y direction
    xmin: 0.0
    ymin: 0.0
    xmax: 5.0
    ymax: 5.0
    interface_center:
        x: 2.5
        y: 2.5
    interface_radius: 1.5
    epsilon_inside: 1.0
    epsilon_outside: 80.0



data_loader:
    batch_size: 64


loss:
    args:
        bound_weight: 8.0e+5                  # Weighting of the loss on the boundaries (float)
        lapl_weight: 8.0e+3
        interface_weight: 3.0e+3                # Weighting of the loss on the Laplacian (float)
        optimizer_lr: 3.e-4   

trainer:
    epochs: 100                            # Number of epochs





