general:
    name_case: 'MSNet3_ks3_rf200.pth'
    data_dir: 'dataset/generated/random_data.npy' 


arch:
    model: "MSNet"
    arch_dir: 'Archs/MSNet_ks3_rf200.yml'
    type: 'MSNet3'


globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 101                                # Number of points in x direction
    nny: 101                                # Number of points in y direction
    xmin: 0.0
    ymin: 0.0
    xmax: 5.0
    ymax: 5.0



data_loader:
    batch_size: 64


loss:
    args:
        bound_weight: 8.0e+2                  # Weighting of the loss on the boundaries (float)
        lapl_weight: 8.0e+5                   # Weighting of the loss on the Laplacian (float)
        optimizer_lr: 2.e-4   

trainer:
    epochs: 250                            # Number of epochs





