general:
    name_case: 'Unet4_ks3_rf200_dirichlet'
    data_dir: 'dataset/generated/random_data.npy' 


arch:
    model: "UNet"
    arch_dir: 'Archs/Unet_ks3_rf200.yml'
    type: 'UNet4'


globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 101                                # Number of points in x direction
    nny: 101                                # Number of points in y direction
    xmin: 0.0
    ymin: 0.0
    xmax: 5.0
    ymax: 5.0



data_loader:
    batch_size: 64


loss:
    args:
        bound_weight: 8.0e+5                  # Weighting of the loss on the boundaries (float)
        lapl_weight: 8.0e+4                   # Weighting of the loss on the Laplacian (float)
        optimizer_lr: 1.e-4                   # Learning rate of the optimizer (float)   

trainer:
    epochs: 150                            # Number of epochs





