globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 101                                # Number of points in x direction
    nny: 101                                # Number of points in y direction
    xmin: 0.0
    xmax: 5.0
    ymin: 0.0
    ymax: 5.0
    interface_center:
        x: 0.5e-2
        y: 0.5e-2
    interface_radius: 2.0e-3
    epsilon_inside: 1
    epsilon_outside: 80

arch:
    scales:
        scale_0: [[1, 30, 20], [40, 30, 1]]
        scale_1: [[20, 20, 20], [40, 20, 20]]
        scale_2: [[20, 16, 16, 20], [40, 16, 16, 20]]
        scale_3: [[20, 20, 20], [40, 20, 20]]
        scale_4: [[20, 60, 20]]
    kernel_sizes: 3
        

data_loader:
    batch_size: 64


loss:
    args:
        bound_weight: 5.0e+7                   # Weighting of the loss on the boundaries (float)
        lapl_weight: 2.0e+15                 # Weighting of the loss on the Laplacian (float)
        optimizer_lr: 1.e-6    

trainer:
    epochs: 500                              # Number of epochs