general:
    name_case: 'interface_Unet300'
    data_dir: 'dataset/generated/random_data.npy' 


arch:
    model: "UNet"
    arch_dir: 'Unet_ks3_rf300.yml'
    type: 'UNet4'


globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 101                                # Number of points in x direction
    nny: 101                                # Number of points in y direction
    xmin: 0.0
    ymin: 0.0
    xmax: 5.0
    ymax: 5.0
    interface_center:
        x: 2.5
        y: 2.5
    interface_radius: 1.5
    epsilon_inside: 1.0
    epsilon_outside: 80.0



data_loader:
    batch_size: 64


loss:
    args:
        bound_weight: 5.0e+0                  # Weighting of the loss on the boundaries (float)
        lapl_weight: 9.0e+7
        interface_weight: 5.0e+4                # Weighting of the loss on the Laplacian (float)
        optimizer_lr: 2.e-4   

trainer:
    epochs: 41                            # Number of epochs






