globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 101                                # Number of points in x direction
    nny: 101                                # Number of points in y direction
    xmin: 0.0
    xmax: 1.0e-2
    ymin: 0.0
    ymax: 1.0e-2

arch:
    db_file: 'unets_ks3_rf100.yml'          # Database file
    name: 'UNet5'                           # Name of the network in the database file
    args:
        input_res: 101                      # Required argument to define the input res of the network

data_loader:
    data_dir: 'C:\Codigos\poissonSolverCNN\dataset\generated\random_data.npy'   # Dataset path
    batch_size: 64


loss:
    args:
        bound_weight: 1.0                   # Weighting of the loss on the boundaries (float)
        lapl_weight: 2.0e+7                 # Weighting of the loss on the Laplacian (float)

trainer:
    epochs: 30                              # Number of epochs
    save_dir: 'debug/'                      # Output directory
    save_period: 10                         # Output period
    plot_period: 10                         # Period to send plots to TensorBoard

