general:
    name_case: '3D_Unet4_ks3_rf300.pth'
    data_dir: 'dataset/generated/random.npy' 


arch:
    model: "UNet"
    arch_dir: 'Archs/Unet_ks3_rf300.yml'
    type: 'UNet4'


globals:                                   # Domain sizes and others, used to compute global attributes
    nnx: 61                                # Number of points in x direction
    nny: 61                                # Number of points in y direction
    nnz: 61                                # Number of points in z direction
    xmin: 0.0
    xmax: 5.0
    ymin: 0.0
    ymax: 5.0
    zmin: 0.0
    zmax: 5.0



data_loader:
    batch_size: 64


loss:
    type: laplacian
    args:
        bound_weight: 8.0e+2                  # Weighting of the loss on the boundaries (float)
        lapl_weight: 8.0e+5                   # Weighting of the loss on the Laplacian (float)
        inside_weight: 1.0e+1
        optimizer_lr: 5.e-5                   # Learning rate of the optimizer (float)   

trainer:
    epochs: 40                            # Number of epochs


