globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 30                                # Number of points in x direction
    nny: 30                                # Number of points in y direction
    nnz: 30
    xmin: 0.0
    xmax: 1.0e-2
    ymin: 0.0
    ymax: 1.0e-2
    zmin: 0.0
    zmax: 1.0e-2
    

# arch: 
#     type: UNet
#     scales:
#         scale_0: [[1, 30, 20], [40, 30, 1]]
#         scale_1: [[20, 20, 20], [40, 20, 20]]
#         scale_2: [[20, 16, 16, 20], [40, 16, 16, 20]]
#         scale_3: [[20, 20, 20], [40, 20, 20]]
#         scale_4: [[20, 60, 20]]
#     kernel_sizes: 3

arch:
    type: 'MSNet'
    scales:
        scale_0: [2, 30, 30, 1]
        scale_1: [2, 22, 22, 22, 1]
        scale_2: [2, 22, 22, 22, 1]
        scale_3: [1, 30, 30, 1]
    kernel_sizes: 5
        

data_loader:
    batch_size: 64


loss:
    args:
        bound_weight: 1.0                   # Weighting of the loss on the boundaries (float)
        lapl_weight: 2.0e+2                 # Weighting of the loss on the Laplacian (float)
        inside_weight: 5.0e+2
        optimizer_lr: 4.e-2    

trainer:
    epochs: 300                              # Number of epochs


