general:
    name_case: 'interface3d_2'
    data_dir: 'dataset/generated/random.npy' 


arch:
    model: "UNet"
    arch_dir: 'Unet_ks3_rf200.yml'
    type: 'UNet4'


globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 51                                # Number of points in x direction
    nny: 51                                # Number of points in y direction
    nnz: 51
    xmin: 0.0
    xmax: 5.0
    ymin: 0.0
    ymax: 5.0
    zmin: 0.0
    zmax: 5.0
    interface_center:
        x: 2.5
        y: 2.5
        z: 2.5
    interface_radius: 1.
    epsilon_inside: 1.0
    epsilon_outside: 80.0
    


data_loader:
    batch_size: 64


loss:
    type: laplacian
    args:
        bound_weight: 1.0e-3
        interface_weight: 5.0e+1               # Weighting of the loss on the boundaries (float)
        lapl_weight: 2.0e+4                # Weighting of the loss on the Laplacian (float)
        optimizer_lr: 4.e-4 
        inside_weight: 5.0e+10

trainer:
    epochs: 50                              # Number of epochs
