globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 40                                # Number of points in x direction
    nny: 40                                # Number of points in y direction
    nnz: 40
    xmin: 0.0
    xmax: 1.0e-2
    ymin: 0.0
    ymax: 1.0e-2
    zmin: 0.0
    zmax: 1.0e-2
    

arch:
    type: 'UNet'
    args:
    scales:
        scale_0: [[1, 14, 14, 14, 14, 14, 14, 14, 14, 14, 12], [24, 14, 14, 14, 14, 14, 14, 14, 14, 14, 1]]
        scale_1: [[12, 14, 14, 14, 14, 14, 14, 14, 14, 14, 12], [24, 14, 14, 14, 14, 14, 14, 14, 14, 14, 12]]
        scale_2: [12, 16, 16, 16, 16, 16, 16, 16, 16, 16, 12]
    kernel_sizes: [3, 3, 3, 3, 3]



        

data_loader:
    batch_size: 64


loss:
    args:
        bound_weight: 1.0                   # Weighting of the loss on the boundaries (float)
        lapl_weight: 2.0e+7                 # Weighting of the loss on the Laplacian (float)
        optimizer_lr: 4.e-4 
        inside_weight: 2.0e+5

trainer:
    epochs: 50                              # Number of epochs
