general:
    name_case: 'interface3d_5'
    data_dir: 'dataset/generated/rhs_data.npy' 
    target_dir: 'dataset/generated/potentials_data.npy'


arch:
    model: "UNet"
    arch_dir: 'Unet_ks3_rf300.yml'
    type: 'UNet4'


globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 61                                # Number of points in x direction
    nny: 61                                # Number of points in y direction
    nnz: 61
    xmin: -2.5
    xmax: 2.5
    ymin: -2.5
    ymax: 2.5
    zmin: -2.5
    zmax: 2.5
    interface_center:
        x: 0.0
        y: 0.0
        z: 0.0
    interface_radius: 1.0
    epsilon_inside: 1.0
    epsilon_outside: 80.0
    


data_loader:
    batch_size: 64


loss:
    type: laplacian
    args:
        bound_weight: 1.0e-3
        interface_weight: 5.0e+1               # Weighting of the loss on the boundaries (float)
        lapl_weight: 2.0e+8                # Weighting of the loss on the Laplacian (float)
        inside_weight: 5.0e+9
        optimizer_lr: 4.e-4 

trainer:
    epochs: 100                              # Number of epochs