general:
    name_case: 'interface3d_1.pth'
    data_dir: 'dataset/generated/domain.npy'


globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 35                                # Number of points in x direction
    nny: 35                                # Number of points in y direction
    nnz: 35
    xmin: 0.0
    xmax: 5.0
    ymin: 0.0
    ymax: 5.0
    zmin: 0.0
    zmax: 5.0
    interface_center:
        x: 2.5
        y: 2.5
        z: 2.5
    interface_radius: 1.5
    epsilon_inside: 1.0
    epsilon_outside: 80.0
    

# arch:
#     type: 'MSNet'
#     scales:
#         scale_0: [2, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 1]
#         scale_1: [2, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 1]
#         scale_2: [1, 16, 18, 18, 18, 18, 18, 18, 18, 18, 18, 16, 16, 16, 1]
#     kernel_sizes: 3


arch: 
    type: UNet
    scales:
        scale_0: [[1, 30, 20], [40, 30, 1]]
        scale_1: [[20, 20, 20], [40, 20, 20]]
        scale_2: [[20, 16, 16, 20], [40, 16, 16, 20]]
        scale_3: [[20, 20, 20], [40, 20, 20]]
        scale_4: [20, 60, 20]
    kernel_sizes: 3

     

data_loader:
    batch_size: 64


loss:
    type: laplacian
    args:
        bound_weight: 5.0e+0
        interface_weight: 5.0e+3               # Weighting of the loss on the boundaries (float)
        lapl_weight: 2.0e+4                # Weighting of the loss on the Laplacian (float)
        optimizer_lr: 4.e-4 
        inside_weight: 1.0e+7

trainer:
    epochs: 50                              # Number of epochs
