general:
    name_case: 'Dirichlet_Unet4_ks3_rf400_3D'
    data_dir: 'dataset/generated/random_data.npy' 


arch:
    model: "UNet"
    arch_dir: 'Archs/Unet_ks3_rf400.yml'
    type: 'UNet4'


globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 51                                # Number of points in x direction
    nny: 51                                # Number of points in y direction
    nnz: 51
    xmin: 0.0
    ymin: 0.0
    xmax: 5.0
    ymax: 5.0
    zmin: 0.0
    zmax: 5.0



data_loader:
    batch_size: 64


loss:
    args:
        bound_weight: 9.0e+11                  # Weighting of the loss on the boundaries (float)
        lapl_weight: 5.0e+6                   # Weighting of the loss on the Laplacian (float)
        optimizer_lr: 4.e-5                   # Learning rate of the optimizer (float)   

trainer:
    epochs: 31                            # Number of epochs