general:
    name_case: '3D_Unet4_ks3_rf200'
    data_dir: 'dataset/generated/data.npy' 
    target_dir: 'dataset/generated/potentials_data.npy'


arch:
    model: "UNet"
    arch_dir: 'Unet_ks3_rf200.yml'
    type: 'UNet4'


globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 51                                # Number of points in x direction
    nny: 51                                # Number of points in y direction
    nnz: 51
    xmin: -1.0
    xmax: 1.0
    ymin: -1.0
    ymax: 1.0
    zmin: -1.0
    zmax: 1.0
    interface_center:
        x: 0.0
        y: 0.0
        z: 0.0
    interface_radius: 0.3
    epsilon_inside: 1.0
    epsilon_outside: 80.0

    


data_loader:
    batch_size: 64


loss:
    type: laplacian
    args:
        bound_weight: 1.0e+0              # Weighting of the loss on the boundaries (float)
        interface_weight: 1.0e+5             # Weighting of the loss on the boundaries (float)
        lapl_weight: 1.0e+5               # Weighting of the loss on the Laplacian (float)
        inside_weight: 5.0e+9
        optimizer_lr: 1.e-4 

trainer:
    epochs: 20                              # Number of epochs