globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 30                                # Number of points in x direction
    nny: 30                                # Number of points in y direction
    nnz: 30
    xmin: 0.0
    xmax: 1.0e-2
    ymin: 0.0
    ymax: 1.0e-2
    zmin: 0.0
    zmax: 1.0e-2
    

# arch: 
#     type: UNet
#     scales:
#         scale_0: [[1, 20, 20, 30], [60, 20, 20, 1]]
#         scale_1: [[30, 30, 30, 30], [70, 30, 30]]
#         scale_2: [30, 40, 40]
#     kernel_sizes: [3, 3, 3, 3, 3]

arch:
    type: 'MSNet'
    scales:
        scale_0: [2, 58, 58, 1]
        scale_1: [2, 58, 58, 1]
        scale_2: [1, 40, 40, 40, 1]
    kernel_sizes: 3
        

data_loader:
    batch_size: 64


loss:
    args:
        bound_weight: 1.0                   # Weighting of the loss on the boundaries (float)
        lapl_weight: 2.0e+4                 # Weighting of the loss on the Laplacian (float)
        inside_weight: 5.0e+2
        optimizer_lr: 4.e-1    

trainer:
    epochs: 50                              # Number of epochs


