general:
    name_case: 'Unet4_ks3_rf200.pth'
    data_dir: 'dataset/generated/random.npy' 


arch:
    model: "UNet"
    arch_dir: 'Archs/Unet_ks3_rf50.yml'
    type: 'UNet4'


globals:                                    # Domain sizes and others, used to compute global attributes
    nnx: 35                                # Number of points in x direction
    nny: 35                                # Number of points in y direction
    nnz: 35
    xmin: 0.0
    xmax: 5.0
    ymin: 0.0
    ymax: 5.0
    zmin: 0.0
    zmax: 5.0



data_loader:
    batch_size: 64


loss:
    type: laplacian
    args:
        bound_weight: 5.0e+0
        interface_weight: 5.0e+5               # Weighting of the loss on the boundaries (float)
        lapl_weight: 2.0e+4                # Weighting of the loss on the Laplacian (float)
        optimizer_lr: 2.e-5 
        inside_weight: 1.0e+7

trainer:
    epochs: 50                              # Number of epochs
